//User Actions Types

//Login  types
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

//Login  types
export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

//Fetch doctor DETAIL
export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

//Doctor Action Types

//Add doctor Types
export const ADD_DOCTOR_REQUEST = "ADD_DOCTOR_REQUEST";
export const ADD_DOCTOR_SUCCESS = "ADD_DOCTOR_SUCCESS";
export const ADD_DOCTOR_FAIL = "ADD_DOCTOR_FAIL";

//Fetch all doctors
export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST";
export const GET_DOCTORS_SUCCESS = "GET_DOCTORS_SUCCESS";
export const GET_DOCTORS_FAIL = "GET_DOCTORS_FAIL";

//Profile Types
export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

//Fetch doctor DETAIL
export const TIMELINE_DETAIL_REQUEST = "TIMELINE_DETAIL_REQUEST";
export const TIMELINE_DETAIL_SUCCESS = "TIMELINE_DETAIL_SUCCESS";
export const TIMELINE_DETAIL_FAIL = "TIMELINE_DETAIL_FAIL";
export const UPDATE_TIMELINE_DETAILS = "UPDATE_TIMELINE_DETAILS";

//Timeline types
export const CREATE_TIMELINE_REQUEST = "CREATE_TIMELINE_REQUEST";
export const CREATE_TIMELINE_SUCCESS = "CREATE_TIMELINE_SUCCESS";
export const CREATE_TIMELINE_FAIL = "CREATE_TIMELINE_FAIL";

export const UPDATE_TIMELINE_REQUEST = "UPDATE_TIMELINE_REQUEST";
export const UPDATE_TIMELINE_SUCCESS = "UPDATE_TIMELINE_SUCCESS";
export const UPDATE_TIMELINE_FAIL = "UPDATE_TIMELINE_FAIL";
